---
- name: Ensure IP forwarding is enabled
  hosts: k8s_nodes
  become: yes
  tasks:
    - name: Enable IP forwarding
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes
      register: ip_forwarding_status

    - name: Display change status
      debug:
        msg: "IP forwarding has been enabled."
      when: ip_forwarding_status.changed

    - name: Display no change needed
      debug:
        msg: "IP forwarding was already enabled."
      when: not ip_forwarding_status.changed
